#!/usr/bin/env python3
"""Render a scope_of_work.json into a clean, printable HTML->PDF report,
via headless Chrome (no pandoc/wkhtmltopdf dependency). Report-only output
— nothing here submits, prices, or commits anything.

Usage:
  python3 render_scope_pdf.py path/to/scope_of_work.json --out report.pdf --title "..."
"""
import argparse
import html
import json
import subprocess
import tempfile
from pathlib import Path

CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

CONFIDENCE_COLOR = {
    "schedule_verified": "#1a7a3c",
    "cross_checked": "#1a7a3c",
    "single_source": "#8a6d1a",
    "vision_count": "#8a6d1a",
    "benchmark_only": "#8a6d1a",
    "unresolved": "#a02020",
}


def esc(s):
    return html.escape(str(s)) if s is not None else ""


def build_html(scope: dict, title: str, subtitle: str) -> str:
    rows = []
    for line in scope["lines"]:
        qty = line["quantity"]
        qty_str = f"{qty:,.2f}".rstrip("0").rstrip(".") if isinstance(qty, float) else (f"{qty:,}" if qty is not None else "&mdash;")
        color = CONFIDENCE_COLOR.get(line["confidence"], "#555")
        cites = "<br>".join(
            f"<span class='cite'>{esc(c['source_file'])} p{c['source_page']}"
            + (f" &mdash; <i>{esc(c['source_snippet'])}</i>" if c.get("source_snippet") else "")
            + "</span>"
            for c in line["citations"]
        ) or "<span class='cite'>n/a (unresolved)</span>"
        note = f"<div class='note'>{esc(line['note'])}</div>" if line.get("note") else ""
        rows.append(f"""
        <tr>
          <td class='div'>{esc(line['csi_division'])}</td>
          <td>
            <div class='item'>{esc(line['item'])}</div>
            {note}
          </td>
          <td class='qty'>{qty_str}</td>
          <td>{esc(line['unit'])}</td>
          <td><span class='pill' style='background:{color}1a;color:{color};border:1px solid {color}55'>{esc(line['confidence'])}</span></td>
          <td class='src'>{cites}</td>
        </tr>""")

    unresolved = sum(1 for l in scope["lines"] if l["confidence"] == "unresolved")
    verified = scope["line_count"] - unresolved

    return f"""<!doctype html><html><head><meta charset="utf-8">
<style>
  body {{ font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1a1a1a; margin: 36px; font-size: 12.5px; }}
  h1 {{ font-size: 19px; margin-bottom: 2px; }}
  .subtitle {{ color: #555; font-size: 12px; margin-bottom: 14px; }}
  .banner {{ background: #fff4e5; border: 1px solid #d99a3a; border-radius: 6px; padding: 10px 14px; margin-bottom: 18px; font-size: 11.5px; }}
  .stats {{ display: flex; gap: 18px; margin-bottom: 16px; }}
  .stat {{ border: 1px solid #ddd; border-radius: 6px; padding: 8px 14px; }}
  .stat b {{ font-size: 16px; display: block; }}
  table {{ width: 100%; border-collapse: collapse; }}
  th {{ text-align: left; background: #f4f4f4; font-size: 10.5px; text-transform: uppercase; letter-spacing: 0.03em; padding: 6px 8px; border-bottom: 2px solid #ccc; }}
  td {{ vertical-align: top; padding: 7px 8px; border-bottom: 1px solid #e5e5e5; font-size: 11.5px; }}
  .div {{ font-weight: 700; color: #555; }}
  .item {{ font-weight: 600; }}
  .qty {{ text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }}
  .note {{ color: #555; font-size: 10.5px; margin-top: 3px; }}
  .pill {{ display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 10px; font-weight: 600; white-space: nowrap; }}
  .src {{ font-size: 10px; color: #444; max-width: 210px; }}
  .cite {{ display: block; margin-bottom: 3px; }}
  footer {{ margin-top: 20px; font-size: 10px; color: #888; }}
</style></head>
<body>
  <h1>{esc(title)}</h1>
  <div class="subtitle">{esc(subtitle)}</div>
  <div class="banner"><b>Report-only.</b> This is a materials/quantity breakdown generated from the real bid attachments for internal review. It does not submit a bid, price a proposal, or commit ENGCO to anything &mdash; every line is either cited to an exact source or explicitly flagged as needing human takeoff.</div>
  <div class="stats">
    <div class="stat"><b>{scope['line_count']}</b>total line items</div>
    <div class="stat"><b>{verified}</b>cited/verified</div>
    <div class="stat"><b>{unresolved}</b>flagged for human takeoff</div>
  </div>
  <table>
    <tr><th>Div</th><th>Item</th><th>Qty</th><th>Unit</th><th>Confidence</th><th>Source</th></tr>
    {"".join(rows)}
  </table>
  <footer>Generated by the ENGCO ONE estimating toolkit &mdash; scripts/estimating/build_kingwood_scope.py &amp; render_scope_pdf.py</footer>
</body></html>"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("scope_json")
    ap.add_argument("--out", required=True)
    ap.add_argument("--title", required=True)
    ap.add_argument("--subtitle", default="")
    args = ap.parse_args()

    scope = json.loads(Path(args.scope_json).read_text())
    doc = build_html(scope, args.title, args.subtitle)

    with tempfile.NamedTemporaryFile("w", suffix=".html", delete=False) as f:
        f.write(doc)
        html_path = f.name

    out_path = str(Path(args.out).resolve())
    subprocess.run([
        CHROME, "--headless", "--disable-gpu",
        f"--print-to-pdf={out_path}",
        "--no-pdf-header-footer",
        "--print-to-pdf-no-header",
        f"file://{html_path}",
    ], check=True, capture_output=True)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
